name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true
      
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Codacy Coverage Reporter
      env:
        CODACY_PROJECT_TOKEN: 688e7c8f14bb419396fe6dfcaffba1ae
      run: |
        curl -L https://coverage.codacy.com/get.sh | bash -s report -r ./AdventOfCode.Tests/coverage.opencover.xml
           
